export const LOGGIN_USER = 'LOGGIN_USER';

export const SHIP_FILTER_PAGE = 'SHIP_FILTER_PAGE';
export const SHIP_FILTER_STATUS = 'SHIP_FILTER_STATUS';
export const SHIP_FILTER_NO = 'SHIP_FILTER_NO';

export const CREATE_SHIPMENTDATA = 'CREATE_SHIPMENTDATA';
