export const LOGGIN_USER = 'LOGGIN_USER';

export const APPS_SIDEBAR = 'APPS_SIDEBAR';
export const APPS_LOADING = 'APPS_LOADING';
export const APPS_MODAL_STATUS = 'APPS_MODAL_STATUS';

export const SHIP_FILTER_PAGE = 'SHIP_FILTER_PAGE';
export const SHIP_FILTER_STATUS = 'SHIP_FILTER_STATUS';
export const SHIP_FILTER_NO = 'SHIP_FILTER_NO';

export const CREATE_SHIPMENTDATA = 'CREATE_SHIPMENTDATA';
